image: docker:latest

services:
  - docker:dind

stages:
  - test

run_tests:
  stage: test
  script:
    - echo "Installing"
    - docker run --rm --volume $PWD:/usr/src/app -w /usr/src/app node:14.8 yarn
    - echo "Running static analysis & code style"
    - docker run --rm --volume $PWD:/usr/src/app -w /usr/src/app node:14.8 yarn run lint
  only:
    - merge_requests